import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
#
# Commented out because it causes errors in development when cache_manifest.json doesn't exist
# Uncomment and run `mix assets.deploy` before building production releases if needed
# config :example_desktop, ExampleDesktopWeb.Endpoint,
#   cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :error

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
