defmodule ExTauri.Hook do
  @moduledoc """
  Provides a LiveView JS hook for bridging Phoenix LiveView with Tauri APIs.

  This module generates the JavaScript hook that enables bidirectional
  communication between Elixir/LiveView and Tauri's desktop APIs
  (notifications, clipboard, dialogs, file system, etc.).

  ## Setup

  1. Add the hook to your LiveView JS app:

      ```javascript
      // assets/js/app.js
      import { TauriHook } from "../vendor/ex_tauri"

      let liveSocket = new LiveSocket("/live", Socket, {
        hooks: { TauriHook },
        // ... other options
      })
      ```

  2. Attach the hook to a DOM element in your LiveView template:

      ```heex
      <div id="tauri-bridge" phx-hook="TauriHook"></div>
      ```

  3. Use `ExTauri.Hook.push_command/3` in your LiveView to invoke Tauri APIs:

      ```elixir
      def handle_event("send_notification", _params, socket) do
        socket = ExTauri.Hook.push_command(socket, "notification", %{
          title: "Hello",
          body: "World"
        })
        {:noreply, socket}
      end
      ```

  ## How It Works

  - LiveView pushes a `"tauri_command"` event to the JS hook via `push_event/3`
  - The JS hook receives the event and calls the appropriate Tauri API
  - Results are sent back to the LiveView as `"tauri_response"` events
  - Errors are sent back as `"tauri_error"` events

  ## Supported Commands

  The following command types are supported (requires corresponding Tauri plugins):

  | Command         | Plugin Required                  | Description                    |
  |-----------------|----------------------------------|--------------------------------|
  | `notification`  | `tauri-plugin-notification`      | Send system notifications      |
  | `clipboard_write` | `tauri-plugin-clipboard-manager` | Write to clipboard           |
  | `clipboard_read`  | `tauri-plugin-clipboard-manager` | Read from clipboard          |
  | `dialog_open`   | `tauri-plugin-dialog`            | Open file dialog               |
  | `dialog_save`   | `tauri-plugin-dialog`            | Save file dialog               |
  | `dialog_message`| `tauri-plugin-dialog`            | Message dialog (alert/confirm) |
  | `os_info`       | `tauri-plugin-os`                | Get OS information             |
  | `fs_read`       | `tauri-plugin-fs`                | Read a file                    |
  | `fs_write`      | `tauri-plugin-fs`                | Write a file                   |
  | `fs_exists`     | `tauri-plugin-fs`                | Check if path exists           |
  | `fs_readdir`    | `tauri-plugin-fs`                | List directory entries          |
  | `fs_remove`     | `tauri-plugin-fs`                | Remove a file                  |
  | `fs_mkdir`      | `tauri-plugin-fs`                | Create a directory             |
  | `shell_open`    | `tauri-plugin-shell`             | Open URL/path in default app   |
  | `shell_exec`    | `tauri-plugin-shell`             | Execute a scoped command       |

  Custom Tauri commands registered via `#[tauri::command]` can also be invoked
  by using `"invoke"` as the command type with a `cmd` field in the payload.
  """

  @doc """
  Pushes a Tauri command to the JS hook via LiveView's `push_event/3`.

  The command will be executed on the Tauri side and the result will be
  sent back as a `"tauri_response"` event that you can handle with
  `handle_event("tauri_response", payload, socket)`.

  ## Parameters

    * `socket` - The LiveView socket
    * `command` - The command type (e.g., "notification", "clipboard_write")
    * `payload` - A map of command parameters

  ## Examples

      # Send a notification
      push_command(socket, "notification", %{title: "Hello", body: "World"})

      # Read clipboard
      push_command(socket, "clipboard_read", %{})

      # Open file dialog
      push_command(socket, "dialog_open", %{
        title: "Select a file",
        filters: [%{name: "Images", extensions: ["png", "jpg"]}]
      })

      # Invoke a custom Tauri command
      push_command(socket, "invoke", %{cmd: "my_custom_command", args: %{key: "value"}})
  """
  @compile {:no_warn_undefined, Phoenix.LiveView}

  def push_command(socket, command, payload \\ %{}) do
    ref = System.unique_integer([:positive]) |> to_string()

    Phoenix.LiveView.push_event(socket, "tauri_command", %{
      ref: ref,
      command: command,
      payload: payload
    })
  end

  @doc """
  Returns the JavaScript source code for the TauriHook.

  This can be used to generate the vendor file at build time or
  to inline the hook in your application.

  ## Example

      # In a mix task or build script:
      File.write!("assets/vendor/ex_tauri.js", ExTauri.Hook.js_source())
  """
  def js_source do
    ~S"""
    // ExTauri LiveView Hook — Bridge between Phoenix LiveView and Tauri APIs
    // Generated by ExTauri. See ExTauri.Hook for documentation.

    function isTauri() {
      return window.__TAURI__ !== undefined;
    }

    // Allowlist of valid commands to prevent arbitrary command injection
    const ALLOWED_COMMANDS = new Set([
      "notification", "clipboard_write", "clipboard_read",
      "dialog_open", "dialog_save", "dialog_message",
      "os_info", "fs_read", "fs_write", "fs_exists",
      "fs_readdir", "fs_remove", "fs_mkdir",
      "shell_open", "shell_exec", "invoke"
    ]);

    async function execCommand(command, payload) {
      if (!isTauri()) {
        throw new Error("Not running in Tauri — commands are only available in the desktop app");
      }

      if (!ALLOWED_COMMANDS.has(command)) {
        throw new Error(`Blocked unknown Tauri command: ${command}`);
      }

      switch (command) {
        case "notification": {
          const { sendNotification, isPermissionGranted, requestPermission } =
            await import("@tauri-apps/plugin-notification");
          let permitted = await isPermissionGranted();
          if (!permitted) {
            const permission = await requestPermission();
            permitted = permission === "granted";
          }
          if (permitted) {
            sendNotification(payload);
            return { status: "sent" };
          }
          return { status: "denied" };
        }

        case "clipboard_write": {
          const { writeText } = await import("@tauri-apps/plugin-clipboard-manager");
          await writeText(payload.text);
          return { status: "ok" };
        }

        case "clipboard_read": {
          const { readText } = await import("@tauri-apps/plugin-clipboard-manager");
          const text = await readText();
          return { text };
        }

        case "dialog_open": {
          const { open } = await import("@tauri-apps/plugin-dialog");
          const result = await open(payload);
          return { path: result };
        }

        case "dialog_save": {
          const { save } = await import("@tauri-apps/plugin-dialog");
          const result = await save(payload);
          return { path: result };
        }

        case "dialog_message": {
          const { message, ask, confirm } = await import("@tauri-apps/plugin-dialog");
          if (payload.type === "ask") {
            const result = await ask(payload.message, payload);
            return { result };
          } else if (payload.type === "confirm") {
            const result = await confirm(payload.message, payload);
            return { result };
          } else {
            await message(payload.message, payload);
            return { status: "ok" };
          }
        }

        case "os_info": {
          const { platform, arch, version, type: osType, locale } =
            await import("@tauri-apps/plugin-os");
          return {
            platform: platform(),
            arch: arch(),
            version: version(),
            os_type: osType(),
            locale: await locale(),
          };
        }

        case "fs_read": {
          const { readTextFile } = await import("@tauri-apps/plugin-fs");
          const opts = {};
          if (payload.baseDir) opts.baseDir = payload.baseDir;
          const contents = await readTextFile(payload.path, opts);
          return { contents };
        }

        case "fs_write": {
          const { writeTextFile } = await import("@tauri-apps/plugin-fs");
          const opts = {};
          if (payload.baseDir) opts.baseDir = payload.baseDir;
          if (payload.append) opts.append = true;
          await writeTextFile(payload.path, payload.contents, opts);
          return { status: "ok" };
        }

        case "fs_exists": {
          const { exists } = await import("@tauri-apps/plugin-fs");
          const opts = {};
          if (payload.baseDir) opts.baseDir = payload.baseDir;
          const result = await exists(payload.path, opts);
          return { exists: result };
        }

        case "fs_readdir": {
          const { readDir } = await import("@tauri-apps/plugin-fs");
          const opts = {};
          if (payload.baseDir) opts.baseDir = payload.baseDir;
          const entries = await readDir(payload.path, opts);
          return { entries };
        }

        case "fs_remove": {
          const { remove } = await import("@tauri-apps/plugin-fs");
          const opts = {};
          if (payload.baseDir) opts.baseDir = payload.baseDir;
          await remove(payload.path, opts);
          return { status: "ok" };
        }

        case "fs_mkdir": {
          const { mkdir } = await import("@tauri-apps/plugin-fs");
          const opts = { recursive: payload.recursive !== false };
          if (payload.baseDir) opts.baseDir = payload.baseDir;
          await mkdir(payload.path, opts);
          return { status: "ok" };
        }

        case "shell_open": {
          const { open } = await import("@tauri-apps/plugin-shell");
          await open(payload.url);
          return { status: "ok" };
        }

        case "shell_exec": {
          const { Command } = await import("@tauri-apps/plugin-shell");
          const cmd = Command.create(payload.program, payload.args || []);
          const output = await cmd.execute();
          return { stdout: output.stdout, stderr: output.stderr, code: output.code };
        }

        case "invoke": {
          const { invoke } = await import("@tauri-apps/api/core");
          const result = await invoke(payload.cmd, payload.args || {});
          return { result };
        }

        default:
          throw new Error(`Unknown Tauri command: ${command}`);
      }
    }

    export const TauriHook = {
      mounted() {
        this.handleEvent("tauri_command", async ({ ref, command, payload }) => {
          try {
            const result = await execCommand(command, payload);
            this.pushEvent("tauri_response", { ref, command, ...result });
          } catch (error) {
            this.pushEvent("tauri_error", {
              ref,
              command,
              error: error.message || String(error),
            });
          }
        });
      },
    };
    """
  end
end
