defmodule ExTauri.Plugins do
  @moduledoc """
  Installs Tauri plugins into an existing `src-tauri/` project.

  Adding a Tauri plugin by hand takes three coordinated edits: a crate in
  `src-tauri/Cargo.toml`, a `.plugin(...)` registration in `src-tauri/src/main.rs`,
  and permissions in `src-tauri/capabilities/default.json`. This module (used by
  `mix ex_tauri.add`) performs all three, idempotently, so the Elixir-side API
  modules work without touching Rust.

  ## Supported plugins

  | Name              | Elixir API               | What it enables                        |
  |-------------------|--------------------------|----------------------------------------|
  | `dialog`          | `ExTauri.Dialog`         | Native file/message dialogs            |
  | `fs`              | `ExTauri.Filesystem`     | Filesystem access outside the sandbox  |
  | `clipboard`       | `ExTauri.Clipboard`      | Read/write the system clipboard        |
  | `os`              | `ExTauri.OS`             | OS platform/arch/locale info           |
  | `global-shortcut` | `ExTauri.GlobalShortcut` | App-wide keyboard shortcuts            |
  | `autostart`       | `ExTauri.Autostart`      | Launch at login                        |
  | `process`         | `ExTauri.App`            | Exit/relaunch the app                  |
  | `updater`         | `ExTauri.Updater`        | Check for and install updates          |
  | `window`          | `ExTauri.Window`         | Runtime window management permissions  |

  `window` is a pseudo-plugin: window management is part of Tauri core, so it
  only adds the capability permissions (projects generated by current versions
  of `mix ex_tauri.install` already include them).
  """

  @registry %{
    "dialog" => %{
      crate: "tauri-plugin-dialog",
      init: "tauri_plugin_dialog::init()",
      permissions: ["dialog:default"],
      api: "ExTauri.Dialog"
    },
    "fs" => %{
      crate: "tauri-plugin-fs",
      init: "tauri_plugin_fs::init()",
      permissions: ["fs:default"],
      api: "ExTauri.Filesystem"
    },
    "clipboard" => %{
      crate: "tauri-plugin-clipboard-manager",
      init: "tauri_plugin_clipboard_manager::init()",
      permissions: [
        "clipboard-manager:allow-read-text",
        "clipboard-manager:allow-write-text"
      ],
      api: "ExTauri.Clipboard"
    },
    "os" => %{
      crate: "tauri-plugin-os",
      init: "tauri_plugin_os::init()",
      permissions: ["os:default"],
      api: "ExTauri.OS"
    },
    "global-shortcut" => %{
      crate: "tauri-plugin-global-shortcut",
      init: "tauri_plugin_global_shortcut::Builder::new().build()",
      permissions: [
        "global-shortcut:allow-register",
        "global-shortcut:allow-unregister",
        "global-shortcut:allow-is-registered"
      ],
      api: "ExTauri.GlobalShortcut"
    },
    "autostart" => %{
      crate: "tauri-plugin-autostart",
      init:
        "tauri_plugin_autostart::init(tauri_plugin_autostart::MacosLauncher::LaunchAgent, None)",
      permissions: [
        "autostart:allow-enable",
        "autostart:allow-disable",
        "autostart:allow-is-enabled"
      ],
      api: "ExTauri.Autostart"
    },
    "process" => %{
      crate: "tauri-plugin-process",
      init: "tauri_plugin_process::init()",
      permissions: ["process:default"],
      api: "ExTauri.App"
    },
    "updater" => %{
      crate: "tauri-plugin-updater",
      init: "tauri_plugin_updater::Builder::new().build()",
      permissions: ["updater:default"],
      api: "ExTauri.Updater"
    },
    "window" => %{
      crate: nil,
      init: nil,
      permissions: [
        "core:default",
        "core:window:allow-minimize",
        "core:window:allow-maximize",
        "core:window:allow-unmaximize",
        "core:window:allow-toggle-maximize",
        "core:window:allow-set-fullscreen",
        "core:window:allow-set-title",
        "core:window:allow-set-size",
        "core:window:allow-center",
        "core:window:allow-set-focus",
        "core:window:allow-hide",
        "core:window:allow-show",
        "core:window:allow-set-always-on-top",
        "core:window:allow-set-resizable",
        "core:window:allow-start-dragging"
      ],
      api: "ExTauri.Window"
    }
  }

  # Friendly aliases accepted on the command line.
  @aliases %{
    "clipboard-manager" => "clipboard",
    "global_shortcut" => "global-shortcut",
    "globalshortcut" => "global-shortcut",
    "filesystem" => "fs",
    "app" => "process"
  }

  @doc "Returns the list of plugin names that can be installed."
  def known, do: @registry |> Map.keys() |> Enum.sort()

  @doc "Normalizes a user-supplied plugin name to a registry key, or nil."
  def normalize(name) do
    name = name |> String.trim() |> String.downcase()
    name = Map.get(@aliases, name, name)
    if Map.has_key?(@registry, name), do: name, else: nil
  end

  @doc "Returns the registry entry for a plugin name (already normalized)."
  def spec(name), do: Map.fetch!(@registry, name)

  @doc """
  Installs the given plugins into the `src-tauri/` project under `base_dir`.

  Patches `Cargo.toml`, `src/main.rs`, and `capabilities/default.json` for each
  plugin. All edits are idempotent — installing an already-installed plugin is
  a no-op. Raises with an actionable message on unknown plugin names or a
  missing `src-tauri/` directory.
  """
  def add!(names, base_dir \\ File.cwd!()) do
    src_tauri = Path.join(base_dir, "src-tauri")

    unless File.dir?(src_tauri) do
      raise """
      Could not find src-tauri directory in #{base_dir}.

      Run `mix ex_tauri.install` first to set up the Tauri project.
      """
    end

    normalized =
      Enum.map(names, fn name ->
        normalize(name) ||
          raise """
          Unknown Tauri plugin: #{inspect(name)}

          Available plugins: #{Enum.join(known(), ", ")}
          """
      end)

    Enum.map(normalized, fn name ->
      plugin = spec(name)

      if plugin.crate, do: add_cargo_dependency(src_tauri, plugin.crate)
      if plugin.init, do: add_plugin_init(src_tauri, plugin.init)
      add_permissions(src_tauri, plugin.permissions)

      {name, plugin}
    end)
  end

  defp add_cargo_dependency(src_tauri, crate) do
    cargo_path = Path.join(src_tauri, "Cargo.toml")
    content = File.read!(cargo_path)

    if String.contains?(content, crate) do
      :already_present
    else
      unless String.contains?(content, "[dependencies]") do
        raise "Could not find a [dependencies] section in #{cargo_path}"
      end

      # Plugins version independently from the Tauri core crate, so pin to the
      # major version only (same policy as the generated Cargo.toml).
      updated =
        String.replace(
          content,
          "[dependencies]\n",
          "[dependencies]\n#{crate} = \"2\"\n",
          global: false
        )

      File.write!(cargo_path, updated)
      :added
    end
  end

  defp add_plugin_init(src_tauri, init) do
    main_rs_path = Path.join([src_tauri, "src", "main.rs"])
    content = File.read!(main_rs_path)

    if String.contains?(content, init) do
      :already_present
    else
      anchor = "tauri::Builder::default()"

      unless String.contains?(content, anchor) do
        raise """
        Could not find `#{anchor}` in #{main_rs_path}.

        Add the plugin registration manually inside the builder chain:

            .plugin(#{init})
        """
      end

      updated =
        String.replace(
          content,
          anchor,
          "#{anchor}\n        .plugin(#{init})",
          global: false
        )

      File.write!(main_rs_path, updated)
      :added
    end
  end

  defp add_permissions(src_tauri, permissions) do
    capabilities_path = Path.join([src_tauri, "capabilities", "default.json"])

    unless File.exists?(capabilities_path) do
      raise """
      Could not find #{capabilities_path}.

      Run `mix ex_tauri.install` first to generate the capabilities file.
      """
    end

    capabilities = capabilities_path |> File.read!() |> Jason.decode!()
    existing = Map.get(capabilities, "permissions", [])
    missing = Enum.reject(permissions, &(&1 in existing))

    if missing == [] do
      :already_present
    else
      capabilities
      |> Map.put("permissions", existing ++ missing)
      |> Jason.encode!(pretty: true)
      |> then(&File.write!(capabilities_path, &1))

      :added
    end
  end
end
