defmodule ExTauri.Sidecar.DevServer do
  @moduledoc """
  Default sidecar shim. Runs a dev-server command directly inside the Tauri
  window so hot/live reload works, with no release build.

  The command defaults to `mix phx.server` but is configurable, so ExTauri is
  not tied to Phoenix:

      config :ex_tauri, :dev_command, ~w(mix francis.server)

  A command may be given as a list of arguments (recommended) or a raw string.
  """

  @behaviour ExTauri.Sidecar

  @default_command ~w(mix phx.server)

  @impl true
  def script(%{project_root: root}) do
    """
    #!/bin/sh
    # Dev sidecar generated by ExTauri. Runs the configured dev-server command
    # directly so hot reload works inside the Tauri window. Regenerated on each
    # `mix ex_tauri.dev`; production builds overwrite this with a Burrito binary.
    cd "#{root}" || exit 1
    exec #{command()}
    """
  end

  @doc """
  The dev-server command as a shell string, from `config :ex_tauri, :dev_command`.
  """
  def command do
    case Application.get_env(:ex_tauri, :dev_command, @default_command) do
      command when is_binary(command) -> command
      command when is_list(command) -> Enum.join(command, " ")
    end
  end
end
